CREATE TABLE IF NOT EXISTS tags (
		id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		"name" varchar NOT NULL,
		device_id int NOT NULL,
		regexp varchar NOT NULL,
		compare_type varchar(5) NOT NULL,
		value varchar NOT NULL,
		array_index int NOT NULL,
		"subject" varchar NOT NULL,
		severity_level varchar(10) NOT NULL DEFAULT 'info',
		created_at timestamp without time zone NULL,
		updated_at timestamp without time zone NULL,
		deleted_at timestamp without time zone NULL,
		CONSTRAINT tags_pk PRIMARY KEY (id),
		CONSTRAINT tags_name_unique UNIQUE ("name")
	);

