CREATE TABLE IF NOT EXISTS messages (
		id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		got_at timestamp NOT NULL,
		device_id int NOT NULL,
		message text NOT NULL,
		message_type varchar NOT NULL,
		severity_level varchar(10) NOT NULL DEFAULT 'info',
        component varchar(30),
		CONSTRAINT messages_pk PRIMARY KEY (id)
	);

