CREATE TABLE IF NOT EXISTS users (
		id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		email varchar(320) NOT NULL,
		"password" bytea NOT NULL,
		"name" varchar NOT NULL,
		created_at timestamp without time zone NULL,
		updated_at timestamp without time zone NULL,
		deleted_at timestamp without time zone NULL,
		CONSTRAINT users_pk PRIMARY KEY (id),
		CONSTRAINT users_email_unique UNIQUE (email)
	);

